### ISSUE TITLE
local session identifier

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi-vle#1]
It would be beneficial to include a local session identifier from Moodle or Blackboard so that student activity from a single session can be easily related together. This allows us to derive session information such as session time, which is useful in addition to aggregating individual events. The ability to do this is dependent on whether it is supported by each VLE.

**Comment by arc12** [comment]
xAPI context.registration may be a suitable place for this:
> A registration could be considered to be an attempt, a session, or could span
multiple Activities.

But we'd need to be specific, within the scope which xAPI gives us,

**Comment by ds10** [comment]
Did we decide on this weeks call to go with context.registration ? I've added it to this weeks dev branch in the common structures document to discuss at next call

**Comment by MiroslavKratchounov** [comment]
The context.registration is of UUID type and session ids coming from VLE in most cases will be in different format. The Blackboard one is numeric. I suppose we can introduce another extension like: http://xapi.jisc.ac.uk/extension/sessionId.
