### ISSUE TITLE
Use of extensions not appropriate where fields are used for analytics data pipeline

### ISSUE THREAD

**Issue by christoffballard** [jiscdev/xapi-vle#10]
Currently, xAPI extensions are used to pass the row of the moodle logstore to which the statement relates. Clearly, this will be different to Blackboard, and so any fields which are required from this should be incorporated into the structured xAPI receipe, so that the analytics data pipeline can use it consistently regardless of source system. One example is the parent id of the course to which the activity relates. It should be possible to obtain this from the xAPI statement and not by referencing a field in the supplier-specific extension.

**Comment by wilmTap** [comment]
#2

**Comment by wilmTap** [comment]
Platform independence is addressed in issue #24 and pull request #23 
The parent issue is addressed in #2
