### ISSUE TITLE
Suggest - .md document granularity and scope

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#11]
[a partial repeat of a basecamp post with some more comment]

I'd like to suggest documentation is structured as follows, which de-couples three different aspects according to use and lifecycle:
- a single document which describes how the xAPI data structures are to be used (e.g. agent, context) in general terms. This should be the most stable, revision-wise, and changes "must see". The content would be largely universal across all xAPI statement sources (VLE, library, student app), and extensively referenced from the recipes, hence avoiding repetition and inconsistencies.
- a single document containing the URIs for verbs, object types, extension namespaces etc. These would be sourced from external definitions (e.g. ADL, tin can registry etc), or be newly minted. The document would gather the list of what we can expect to use and see, and cleanly define terms. This would be subject to fairly frequent extension as more recipes and application types come on line. The recipes would defer to this as the master vocabulary and we would expect many of the vocabulary terms to be re-used across multiple recipes and applications (as envisaged in the xAPI spec); this would be the go-to place when creating a new recipe to maximise re-use and consistency.
- multiple documents, one per recipe, where a recipe groups definition of several kinds of statement into  thematic chunks. e.g. combine login, logout and time-out into a single recipe document. I think combining description of sets of statements which share some "business logic" (for want of a better word) will help interpretation. These should be fairly stable once at v1 status but new recipes are likely to be added throughout the pilots (and beyond). Version control could helpfully be applied at recipe level, which will help with impact analysis.

**Comment by michaelwebbjisc** [comment]
yes, makes sense.  That's kind of how I structures the original google doc.

**Comment by wilmTap** [comment]
Having discussed this a bit more with David, how about this for a structure for the whole thing:

Front page
     Overview
     UDD Profile
          Entity
               Field
     Statement property (actor, etc)
          property (ID, etc)
     Platform independent recipe
          object references (xAPI URIs etc)
          object definitions (our own entities)
          -> Platform dependent recipe (xAPI VLE) -> code?
          -> Conversion recipe  -> code?

Where a platform independent recipe would be something along the lines of what's in the [tincan recipe registry](https://registry.tincanapi.com/#profile/17) and also what Adam describes for 'thematic chunks'- logical groupings of several actors, verbs and activities and activity types described as a whole, with the vocabulary identifiers (internal and external), but without the details of the message structure. 
The platform dependent recipes would be pretty much as we have them now: detailed, narrow in scope, with the mapping from internal data to the precise xAPI message.

In terms of making all this stuff, I'd propose going in reverse: start with the platform dependent recipes we already have, derive platform independent ones from them, then derive the statement properties from that.

I'd propose doing all the platform independent stuff over at the UDD repo: it revs slower, it makes it easier to find for 'us', and facilitates making a shiny website for a wider audience further down the line.

Does that sound about right?

**Comment by arc12** [comment]
In reverse order ;-)
I'd prefer a separate repo to UDD because I envisage different revision timetables. I hope UDD will settle down quite quickly. It is the data which is most mature, better-understood, and which will be the stuff we use in anger first. I hope we can move to temporarily-frozen UDD quite quickly. As a secondary consideration, I would expect UDD extracts to generally come from SRSs and the process to involve people with backgrounds quite different to that which xAPI pre-supposes; unification may be more of a distraction that an attraction, even once we've got stability

I'd prefer the platform-specific stuff to be called something like "implementation notes", with "recipe" reserved for the platform-neutral stuff. That is consistent with the TinCan useage. I think it will be helpful to make this distinction very clear.

I think "vle" is a problematical distinction. Many of the recipes will not be tied to the (rather fuzzy) definition of a vle. YES, the initial focus is moodle/blackboard, but what about logging use of the student app? So: I think the scope of the repo and its structure should accommodate the reusability of recipes. In practice, I think this is fairly easy to do, with the outline structure (sans UDD) working, but the detail of the presentation and content needing a bit more care to avoid hostages to fortune when we move on to capturing events from non-vles. Maybe there would need to be a vle section in the overview, to signpost the key recipes... maybe. The expanding scope of xAPI use, compounding the fact that it is the data which is least mature, poorly-understood, and not the stuff we use in anger first, is another reason why I expect a different rate of change. Oh, and I think the repo title should change... first impressions do matter.

Adam

**Comment by wilmTap** [comment]
Hmmm, not entirely sure how quickly we can come up with a proper, platform independent recipe we can up with, and how often it'll be revved v.v. the implementations, but don't feel strongly enough to push back, so we'll leave it as is. I'd be happy with the label changes. So the resulting structure would be something like:
```
Front page
	Overview
	UDD Profile
		Entity
		Field
	Statement property (actor, etc)
		property (ID, etc)
	-> recipe
		object references (xAPI URIs etc)
		object definitions (our own entities)
	-> Implementation notes (xAPI VLE) -> code?
	-> Conversion recipe -> code?
```

**Comment by wilmTap** [comment]
Does pull request #26 address the issue?
