### ISSUE TITLE
Add recipe version

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi-vle#14]

**Comment by wilmTap** [comment]
Do we want to make release versions for each recipe, or do we think we need to have to have a 1.0 release for all of them?

**Comment by MiroslavKratchounov** [comment]
My preference would be to use the same Semantic versioning (http://semver.org) across all recipes, otherwise it will be quite a burden on maintaining for each one.

**Comment by ds10** [comment]
Can't find a field for recipe version - mint one?

**Comment by michaelwebbjisc** [comment]
Yes, mint.  Into context?

**Comment by wilmTap** [comment]
Yes, we want to mint one
