### ISSUE TITLE
Develop xAPI recipe for predictive model output

### ISSUE THREAD

**Issue by gryglbrt** [jiscdev/xapi-vle#15]
Develop and document what an xAPI message that contains predictive model output consisting of risk score, student id, module instance id and arbitrary key/value pairs of metrics should look like.

**Comment by wilmTap** [comment]
Hi Gary,

Many thanks for the PR- it looks good to me, and I think it raises a couple of timely questions.

Most questions are pretty general, but one is more to do with my ignorance of the alerting architecture: I'm assuming that the alert xAPI statement goes back into the LRW, but is that for the purpose of further analysis, or is it to get dashboards and the strudent app to pick the alert up and pass on to the user (i.e. using the LRW as a type of message bus)?

On the questions inside the patch:

> Open question on what the value of homepage should be

I thought STUDENT_ID seems a good idea

> Selection of the Verb - receive - is open for discussion

That made me wonder whether we need to model two actions: intervention system sent alert and student read alert. The reason why we might need two is that there could be a significant difference between the two, and that difference is one that’s worth recording if we can. Even if we can’t, the intervention system sending an alert seems a more solid assertion than student receive alert

> Need guidance in general on placement of module instance id, etc

I think that what you have looks good, but I’ll need to check against how Moodle and BB model context at this point. Those have not been reconciled yet (at least not in my mind)

> Need guidance on the value for id

If the statement is retrievable at the intervention system via a URI, that’d be great. If not, just use any domain you control + incremented integer or hash.

> Selection of type - alert - is open for discussion

What you have looks good to me

> Need guidance on extension IRI values

That’d mostly depend on what you can supply and what other folk need to know- that's a good one to discuss more widely.

Also, do people have an opinion about which release this should be aimed at?

**Comment by arc12** [comment]
Folks -
I wonder if the Agent Profile API would be a place to store the triggered alert?
That might avoid some of the over-burden of activity record semantics, but I've not got any experience of the Agent Profile API to back this idea up. Ask Learning Locker folks?

(actually, I don't expect Tribal will use xAPI at all for this since Student Insight aleady has its own API)

Adam

**Comment by gryglbrt** [comment]
Yes the xAPI statement goes back to the LRW. This is so we have a record over time for alerts as well as make them available to LRW clients like the dashboard or student app.

**Comment by wilmTap** [comment]
Looks good to me, I'd be happy to merge, and probably tag it with v1.1 if that's OK with people.

I can see your point, Adam, but the Agent Profile API reads to me like a bulk person object protocol, while an alert seems another thing in a person's activity stream. I guess you could flip the statement around for semantic correctness (" Unicon Alerts StudentID AlertID"), but I'm not sure how much we would win by that.
