### ISSUE TITLE
Repository workflows

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi-vle#17]
After a conversation with Wilbert; it appears one of the difficulties we are having is that this repository and analytics-UDD  have different workflows.

As far as I understand in Analytics-UDD we are encouraged to create a seperate branch when we want to takle  a issues; then we can create a pull request against that issue which can be discussed at the weekly meeting merged in to master if we agree? I understand we then  create tagged releases from master branch?

Will that be the workflow in this repository? I think it would help me to be consistant about the process. The pull request for #15 in to master seems to be following this workflow; but rev1 seems to be ahead of master; which has pulled from a dev branch.

Perhaps easier to talk about at next team meeting

**Comment by arc12** [comment]
+1 for consisttency.

I have no views as to the "best" approach, and happy to be told. There is a link to how ADL does its spec revision workflow on basecamp somewhere.

A few lines of "this is the workflow" process (and possibly also git commands for any others like me who have only ever used git for single-user repos) in the readme.md would be welcome.

**Comment by wilmTap** [comment]
Its the same flow as outlined in [this post on basecamp](https://basecamp.com/2737506/projects/10136653/messages/54066675), and as discussed last Friday:
1. Create an issue, if there isn't one already, to announce what you're going to fix
2. Work on a patch in your own branch, preferably somewhere visible
3. Send a pull request
4. Discuss pull request during Monday stand up
We'll then manage the merge into Master.

We can create a release branch if needed, but I think we could probably get by with just making a release at the agreed point.

**Comment by ds10** [comment]
The workflow was aligned with UDD with #18
