### ISSUE TITLE
clarify domain of vocabulary items

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#27]
re: https://github.com/jiscdev/xapi-vle/blob/master/vocabulary.md

For each subheading, e.g. "verb", I think it would be useful to be explicit about where im xAPI statements the terms are valid. For "verb", this i s rather obvious, and the domain of use can be inferred from recipes, but I think it would help correct interpretation and use. This is partially there already...

I have a hunch that there should also be some re-work of that md page, to reconcile some overlap (I think) between three headings there now: activitty type, object.definition, and object.definition.extension. This will include teasing apart the way we express a link to the parent module/course vs the other kinds of objects within the vle-course-area.

Cheers, Adam

**Comment by wilmTap** [comment]
Do you mean the overlap between xAPI vocab, our own extensions and platform specific extensions?

**Comment by arc12** [comment]
@wilmTap - sorry for being cryptic - no, I mean that the documentation for the vocabularies should specify which xAPI entities they are intended for use with - i,e, exactly where in the JSON. Sometimes this is obvious, sometimes less so. Examples may help but they are not supposed to be normative, and one example per URI is a lot more effort than a dot-notation statement in the vocab doc... and less easy to use,

Adam

**Comment by wilmTap** [comment]
So are you asking for things like 
> verb.id.https://brindlewaye.com/xAPITerms/verbs/loggedin/
in a separate column?

We'll mock something up.

**Comment by arc12** [comment]
Sort of.
For the verbs, it is somewhat obvious but for consistency, I'd add a line such as 
"Useage: verb.id" below the Verbs heading

For other cases it is not always clear.
e.g. some URIs would be valid for context.contextActivities.group.[].definition.type

The same URI may not be valid in other places where xAPI spec talks about activities and types.

I *think* the current vocab page is insufficiently clear... actually, I think being uber-explicit will catch some bugs by reducing the amount of interpolation we all make (differently), and I *think* there are bugs there now ;-)

Cheers, Adam
