### ISSUE TITLE
Check recipes match up to vocab and common structures documents

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi-vle#29]
Common structures and vocab documents where updated last week with request. Check that these updates have been reflected in recipes

**Comment by MiroslavKratchounov** [comment]
I needed to change the extensions for courseArea, ip-address and sessionId to be compliant with xAPI https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#miscext and consistent to how extensions are handled in Moodle examples.
Please refer to latest dev branch https://github.com/jiscdev/xapi-vle/tree/dev.

**Comment by wilmTap** [comment]
Moodle plugin to be updated
