### ISSUE TITLE
Choosable user id?

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi-vle#3]
Should plugin users be able to choose which field is used as the id?  Candidates include the internal vle id, the login name, and an other field with a student id in.

**Comment by arc12** [comment]
In some ways, it doesn't matter, so long as persistence, immutability, and uniqueness apply, and we're able to reconcile a variety of person identifiers to a core student record id. There is an argument which says sites should be enabled to choose an identifier which is easy for them to  map to a core student id.

However, I think the analysis of data may be muddied if we cannot segment xapi statements according to the originating application and the way xAPI is specified, there is a fairly tidy pairing of account.name and account.homePage, which lends itself to representing the application + application-specific-identifier e.g. the VLE identity + a VLE-specific user id. I suspect that will be normal use, and it has a simple interpretation both at data origin and data use.

Clearly, we could encode the identity of the originating application in another way than using account.homePage, but I'm concerned that having several ways of doing things would cause pain. Hence: following the grain of xAPI with the Account object is probably the best place to start off, unless we discover serious issues. Exactly which of the application-level user identifiers, if several, is something which I don't think matters (given immutability etc).

**Comment by michaelwebbjisc** [comment]
The specific problem is there that there is no id which is guaranteed to be immutable.   Only the institution will know what is immutable for any given system.  

To give an example, Moodle's internal id was assumed to be immutable, but some institutions rebuild moodle each year, or each upgrade. 

So I think institutions need to be able to say which field is immutable in the plugin. At least for Moodle.

**Comment by arc12** [comment]
If mutation is unexceptional, do we need to accommodate time-bound mappings back to core student ids? ID recycling is inevitable, I suppose, but for training predictive models we do need to go back in time...

Whatever student identifier is used in xAPI statements, I believe it will become important to identify the application which originated xAPI statements too, so we should be careful that we don't conflate application "home page" with authentication domain etc. This will need to be worked through and explained in the documentation for the use of the xAPI Account object.

**Comment by michaelwebbjisc** [comment]
yes, that's why I want the institution to tell use what is immutable, or as immutable as we can get.  This is really functionality of the plugin, but I want to keep things practical, so it makes sense to include here.

**Comment by wilmTap** [comment]
michaelwebbjisc to update plugin
