### ISSUE TITLE
Propose- include assignment submission and grading into standard recipes

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#31]
See discussion here:
https://basecamp.com/2737506/projects/10136653/messages/55761277

Moodle plugin has:
\mod_assign\event\submission_graded 	AssignmentGraded
\mod_assign\event\assessable_submitted 	AssignmentSubmitted

Similar Bb examples exist at https://github.com/jiscdev/xapi-vle/tree/dev/vle/blackboard

I propose these should become standard recipes, with extension to include the due date for the assignent in the statement for the submission statemen

Cheers, Adam

**Comment by arc12** [comment]
I should probably add that my expectation is that the student id and what I've previously called the course area id is all I'm expecting as mandatory context, i.e. what we can translate to UDD entity instance ids*. While the assignment will certainly have an activity id in the statement, I very much doubt that we'll find many institutions who can map that to coursework components in the SRS. The activity id may be useful for us to figure out resubmissions, but I expect we'd treat it as just an unresolved id.

Obviously we'll also need a standard activity type URI (for object.definition.type) which is vle-independent.

Cheers, Adam

* - which I assume will be there in most recipes.

**Comment by MiroslavKratchounov** [comment]
Here is an example of how this might look like for Blackboard:

"object":{
        "objectType":"Activity",
        "id":"https://jisc.blackboard.com/webapps/gradebook/do/instructor/enterGradeCenter?course_id=_47_1&cvid=fullGC#",
        "definition":{
            "type":"http://adlnet.gov/expapi/activities/module",
            "name":{
                "en-US":"Course 47 Assignment"
            },
            "description":{
                "en-US":"Course 47 Assignment description"
            }
        },
        "extensions": {
       		"http://lrs.learninglocker.net/define/extensions/blackboard_module":{
                "duedate":"2016-02-05T17:59:45.000Z"
             }
        }
    }

We would need to add the extension key to the vocabulary.
