### ISSUE TITLE
New moodle examples for review

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi-vle#35]
The Jisc fork of the plugin emitter is now being developed in Github:

https://github.com/jiscdev/xAPI-Recipe-Emitter/tree/UnifiedRecipes1

The loggedin and loggout recipe output are ready for review in a 'moodle-new-recipes' branch:

https://github.com/jiscdev/xapi-vle/blob/moodle-new-recipees/vle/moodle/login.js

and 

https://github.com/jiscdev/xapi-vle/blob/moodle-new-recipees/vle/moodle/logout.js

**Comment by ryansmith94** [comment]
Made comments directly on your commit to the fork @michaelwebbjisc.
