### ISSUE TITLE
VLE activity which are useful for modeling

### ISSUE THREAD

**Issue by sandeepmjay** [jiscdev/xapi-vle#38]
We have been looking into data coming out of Moodle / Sakai (and now BB). We have found the following "high octane" event types to be useful while tracking student engagement in online courses. We usually create bins for these event types as a part of modeling. It would be great to explore the possibility of including these recipes for v1.2 . 

Course/Module Access            (viewed/read)
Content Access                        (viewed/read)
Assignment  		                (viewed/read, submitted, graded )
Assessment_attempt               (take, submit, graded) 
Discussion/Forum                    (viewed/read, posted)
Lessons / mod_book                (viewed)

I see Miroslav has included some of these recipes already for BB. It would be good to have a conversation on how to make them available in both Moodle and BB. Thoughts?

**Comment by garemoko** [comment]
I think most of these are either included in the main Moodle plugin, or are planned. Those that aren't from your list are:

- course/module read (how is this different to viewed?)
- content access (in Moodle, content is Moodle modules - how are you using the term course and module in this thread?)
- assessment graded (I don't know if this is a Moodle event or not, but it's not on the list of events planned)

discussion posted and lesson viewed are definitely good ones to add.
