### ISSUE TITLE
Check language map consistency

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#39]
Normalise recipes and core (rather than Bb/Moodle) examples to use "en" rather than "en-GB" and/or "en-US"

**Comment by ds10** [comment]
Recipes have been updated and moodle plugin has been updated. I can update the Blackboard examples manually, but are they outputs from a Blackboard plugin? If so it best practice for @MiroslavKratchounov to check the code that is outputting the blackboard recipes and update?

**Comment by MiroslavKratchounov** [comment]
The recipes has been updated. Created a pull request:
 https://github.com/jiscdev/xapi-vle/pull/49
