### ISSUE TITLE
Suggest - redefine scope of this documentation/repo

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#4]
I expect there will be many elements of xAPI usage in general (e.g. use of agent object) and recipes (e.g. log in/off) which are not VLE specific. A consistent approach and a single source of documentation for these would be very useful.

Hence: suggest the repo/documentation is scoped as being about xAPI use in the context of the Jisc LA pilots/service, with the scope and purpose of individual recipes making it clear if they are specific to a VLE vs a library system vs the student app ....

I suspect there will be some things where we do need to  document things which are VLE specific - e.g. the use of the Context object in a VLE is something which will need to be clarified if we are to interpret some of the structure of content and back-links to modules - but I think those can be dealt with as specialisations of a general pattern.

**Comment by michaelwebbjisc** [comment]
Yes, this is definitely focussed on the Jisc LA service, rather than more generally, and it's focus is on what we need to do on a practical level to make the service work.  So if we need VLE specific discussion etc, so long as it's a VLE being used by one of Jisc's institution then that's fine.
