### ISSUE TITLE
Assignment submission duedate extension

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi-vle#41]
I might be missing it, but i don't think we've added the due date extensions to the object vocab:

 "extensions":{
    "http://lrs.learninglocker.net/define/extensions/blackboard_module":{
      "duedate":"2016-02-05T17:59:45.000Z"
    }

also, at the moment it's platform specific, so we'd want to make it generic I would think, so following the patterns of the others:

 "extensions":{
    "http://xapi.jisc.ac.uk/extensions/duedate":{
      "duedate":"2016-02-05T17:59:45.000Z"
    }

**Comment by ds10** [comment]
Added to page and recipes in ds10-patch branch. commit: [b5a4cb](https://github.com/jiscdev/xapi-vle/commit/be5a4cb8d51841ed398d923a83051f2ac6a24154)
