### ISSUE TITLE
IP Address extension is used incorrectly

### ISSUE THREAD

**Issue by fugu13** [jiscdev/xapi-vle#47]
The IP Address extension in the examples shows up with a value of a JSON object with a key "ip-address", as shown below.

```
"http://id.tincanapi.com/extensions/ip-address": {  
    "ip-address":"10.3.3.48"
}
```

However, the IP Address extension used, defined at https://registry.tincanapi.com/#uri/extension/310, is clear that "Value is a string representing an Internet Protocol address (IP address) in either IPv4 or IPv6 format" -- there is no object, and there is no key "ip-address".

That is, the extension should look like the following:

```
"http://id.tincanapi.com/extensions/ip-address": "10.3.3.48"
```

The bad pattern seems to have been reused for a number of the JISC-specific extensions, and should probably be changed there, too. Having a key that repeats part of the extension URI and holds the sole value of the extension holds no value.

**Comment by garemoko** [comment]
+1 from me on changing all of these extensions. It's unnecessary complexity.
