### ISSUE TITLE
Refactor Documentation for Vocabularies  - Extensions vs Values

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#48]
The page https://github.com/jiscdev/xapi-vle/blob/master/vocabulary.md currently has two distinct kinds of URI intermixed, which I think is undesriable from the point of view of clarity.

Kind 1:
URIs for extensions, i.e. identifiers for fields with defined conceptual range

Kind 2:
URIs for values of either xAPI- or extension-defined fields. .i.e. for kinds of thing within the defined conceptual range.

Proposals:
1. re-organise the page to keep these two apart
2. adopt a URI naming convention which keeps these apart (and does not, for example. bracket a set of VLE object types as being "extensions".)

**Comment by wilmTap** [comment]
I think we need to refactor the vocab pages in separate sections or pages for: actors, verbs, objects, context and extensions, and refer to each of these entities from the recipes.
