### ISSUE TITLE
Inconsitent URI pattern in xapi.jisc.ac.uk namespace

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#50]
Some URIs are coined as
http://xapi.jisc.ac.uk/extensions/
others as
http://xapi.jisc.ac.uk/define/extensions/

This seems to be indicative of nothing and a potential source of error.

Propose: be consistent

See also issue #48

**Comment by garemoko** [comment]
I prefer the version without /define/ but i don't care much.

**Comment by wilmTap** [comment]
They're stand-ins, coined in haste. We'll try to get proper and consistent webid URIs going ASAP.

**Comment by wilmTap** [comment]
for any change, make a mapping file from old to new in the documentation (Sandeep)
