### ISSUE TITLE
Extensions documentation should define what it is which sits within each extension

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#51]
examples of "what it is which sits":
a string literal
an object of some type 

Ideally, this should be part of the vocabulary doc, alongside the URI, definition and usage information. 
Don't rely on examples.

This also relates to Russel Duhon's issue about the ip address.

**Comment by garemoko** [comment]
For the ip address example, this is already defined within the tin can registry, but that doesn't mean we shouldn't completely and clearly define it here.
