### ISSUE TITLE
Clarify login event recipe

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#53]
The explanation of the use of object is open to mis-interpretation
"The object defines the item that the user hits when they login into a VLE" and the example could leave someone thinking that the object id is a course (etc) and not the application.

The phrase "A Jisc specific extension details that it is a VLE that is being logged into " is not clearly linked to the example

Also logout page.

BTW, the JSON for the verb fragment is invalid
```
"verb": {
        "id": "https://brindlewaye.com/xAPITerms/verbs/loggedin/",
        "display": {
            "en"
        }
    },
```

**Comment by wilmTap** [comment]
How about

> The object.definition.name and object.definition.definition describe the resource returned to the user after they have performed the logged in event. The object.definition.extensions.http://xapi.jisc.ac.uk/extensions/applicationType is used to identify the system type that is being logged into: a VLE, identified by http://xapi.jisc.ac.uk/define/vle
