### ISSUE TITLE
http://xapi.jisc.ac.uk/extensions/applicationType is misdescribed

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#54]
on https://github.com/jiscdev/xapi-vle/blob/master/vocabulary.md

http://xapi.jisc.ac.uk/extensions/applicationType is misdescribed: its usage is not object.definition.type; it is an extension to object.definition.

Also, consider whether this is a struct or a literal extension.

See also my earlier issue on separating extension and "code-list" vocabulary items.

**Comment by arc12** [comment]
Actually - I think it isn't quite I stated, either.

In particular, the application type (such as vle) is a useful aspect of context. Whereas we can consider it to be a qualification of object for a login event, it might be more attractive to always consider this as being a facet of context, for both of the cases where  the application is the object of an action and when it is more clearly contextual (e.g. accessing a learning resource, etc)

**Comment by garemoko** [comment]
@arc12 right. See https://github.com/jiscdev/xapi-vle/issues/65 for how that might be represented in a statement.

**Comment by wilmTap** [comment]
Message path description is fixed, but more can be done to improve the presentation of the object.definition.type vocabulary. See issue #48
