### ISSUE TITLE
Modelling style - extensions for subtypes

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#55]
example: at present the log in recipe uses http://xapi.jisc.ac.uk/extensions/applicationType to clarify what type of application it was, which is the object.definition.type

An alternative style might just use an extension URI which signals a subtype without encoding what the supertype is in the URI. After all this is already there in the path: object.type.definition.extension
e.g. the extension URI might look like xapi.jisc.ac.uk/extensions/subtype

This could be used whatever the object.definition.type is, which would give us a more consistent place to look, and simplify translation from JSON to a tabular form.  I *think* this would be desiable from my POV as a downstream data processor.

Naturally, the recipes would define expected values for subtype within each super-type.

**Comment by garemoko** [comment]
My preference here is to simply make sure what's used in object.definition.type is as specific as possible. The groupings and hierarchy of these types can be defined in the recipe; they do not need to be included in statements. 

Not using extensions here will make the data easier for Learning Record Consumers to report on without having to be programmed with an understanding of this recipe. It's also less complexity and less characters in the statements.

**Comment by wilmTap** [comment]
We intend to restate the recipes in accordance with the [xAPI Companion Specification for Vocabularies](https://adl.gitbooks.io/companion-specification-for-xapi-vocabularies/content/) which specifies formal (SKOS) relations for those kind of semantics.

**Comment by garemoko** [comment]
That's good, but bear in mind that no products in existence today make use of that companion spec and I'm not aware of any that plan to. There are, however, products that make use of the object.definition.type property. I don't see any advantage of not making that as specific as possible.

**Comment by wilmTap** [comment]
Absolutely; the companion spec profile would just be a means of specifiying the relation of the specific object.definition.type value to other values, so that analysts can aggregate at whatever level of abstraction suits them. 

If people prefer a different way of expressing semantic specialisation, I'm all ears.

**Comment by wilmTap** [comment]
This is about using a generic "http://xapi.jisc.ac.uk/subType" rather than an application specific "http://xapi.jisc.ac.uk/applicationType" in object.definition.extensions so that you can always find subtypes no matter what the object.definition.type is.
