### ISSUE TITLE
session timeout recipe should clarify interpretation as well as expression

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi-vle#56]
At present, the recipe (as for the rest of them) comes from the point of view of how a statement would be composed. This is necessary but we also need to consider the uniquess of interpretation.

In this specific case, I suggest that the point to make is that the use of the verb "abandoned" with an object.definition.type of Application NECESSARILY means a session timeout and nothing else.

This is probably a general point: to make sure the recipes are clear from the POV of data readers as well as data writers.

**Comment by garemoko** [comment]
On this event - we (a group at the hackathon) looked at this in Moodle yesterday and we don't think this is an event that can easily be captured.

**Comment by wilmTap** [comment]
Does Moodle record somewhere that a session has ended- I'd imagine that would be the trigger for sending the statement.

**Comment by garemoko** [comment]
The way the Moodle plugin works is to hook into Moodle's events system. As there isn't an event for this, one would need to be added to Moodle core, which is a lot more hassle both in terms of code and politics.

**Comment by wilmTap** [comment]
OK, will clarify the documentation, but it sounds as if we might want to get rid of the recipe. It seems that it might be better to let the analysts decide at which point a session is dead?
