### ISSUE TITLE
Language for language maps always en?

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#59]
In Moodle, courses and the site have a specific language. Should we use that language for language maps when pulling course name and description, for example?

This is relevant even within the UK e.g. for welsh.

**Comment by wilmTap** [comment]
We've just normalised it in favour of "en" in response to issue #39, under the understanding that other languages follow suit. I take your point that it's best done consistently, however, so I think we ought to start moving to an object and recipe definition that goes beyond examples, and defines ranges of legal values explicitly.
