### ISSUE TITLE
Use context.registration instead of session id extension

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#60]
The standard context property 'registration' is designed to keep track things like sessions. We should use that instead of a session extension. 

Since this has to a UUID, the LMS would likely need to have a look up tables between session id and registration id. This has the added security benefit of not exposing the user's session id in statement data. 

https://github.com/jlowe64/moodle-logstore_xapi/issues/61

**Comment by michaelwebbjisc** [comment]
The requirement to make it a UDD may be blocker in the one for now, so might need to stick to our current implementation for now.

**Comment by ThijsHakkenbergLobster** [comment]
An registration is not necessarily the same as a session. In our LMS, we use session to designate the websession while registration is the assignment (in our case). So I disagree with @garemoko in this case.
