### ISSUE TITLE
Activity type for LMS/VLE (used in login/log out)

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#61]
See https://github.com/jiscdev/xapi-vle/issues/55#issuecomment-214695805
and https://github.com/jlowe64/moodle-logstore_xapi/issues/63

I propose we use the activity type http://id.tincanapi.com/activitytype/lms because this is an existing activity type on Registry. 

I also prefer this over http://xapi.jisc.ac.uk/define/vle because vle has an academic specific use, whereas lms I understand is on equal footing with vle in academia.

**Comment by wilmTap** [comment]
LMS and VLE are UK versus US synonyms. I'm happy with the change.

**Comment by garemoko** [comment]
Ok. Since the identifiers are not language specific, that's a really good argument.

**Comment by wilmTap** [comment]
Make sure there's a mapping (Sandeep)
