### ISSUE TITLE
Extend list of activity types

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#62]
I'd like to have a complete list of defined activity types even for activities not covered by this recipe yet, but which are covered by the existing Moodle plugin. I may add a proposed list to this issue later. 

See https://github.com/jlowe64/moodle-logstore_xapi/issues/64

**Comment by garemoko** [comment]
Current example values:

- http://xapi.jisc.ac.uk/define/extensions/vle/page
- http://xapi.jisc.ac.uk/define/extensions/vle/quiz
- http://xapi.jisc.ac.uk/define/extensions/vle/forum
- http://xapi.jisc.ac.uk/define/extensions/externalURL
- http://xapi.jisc.ac.uk/define/extensions/documents/wordDocument
- http://xapi.jisc.ac.uk/define/extensions/documents/excelDocument
- http://activitystrea.ms/schema/1.0/application (see https://github.com/jiscdev/xapi-vle/issues/61)

**Comment by garemoko** [comment]
Other Moodle modules etc. currently tracked by the main Moodle plugin:

- course
- cmi.interaction (quiz question)
- page
- course
- forum_discussions (a thread of a forum)
- quiz_attempts (only used as a context activity)
- resource (covered by documents above?)
- feedback (coming soon!)
- facetoface (coming soon!)

**Comment by garemoko** [comment]
@MiroslavKratchounov we can certainly draw from there, but that list won't cover everything we need. https://registry.tincanapi.com/ has a longer list, but still won't be complete.

**Comment by MiroslavKratchounov** [comment]
It could be just me but I'm not really sure if it is worth tracking wether a student opened a word, excel document or external link. Does this add any value from analytics perspective?

**Comment by garemoko** [comment]
@MiroslavKratchounov maybe students who use excel more than word are more likely to succeed. Who knows? We need the data to see what data is important. :)

Looking at the Moodle database, the file type is not going to be easy to capture though.

**Comment by wilmTap** [comment]
We'll certainly be expanding the number of activity types, but we've been driven by demand so far: if there's an identified need or evidence of use in institutional datasets, we'll add it. That's more of a prioritisation mechanism than a acceptance criterion, though. What has been an acceptance criterion is whether an activity type spans both BB and Moodle; the recipes are designed to be platform independent.

As part of the hackathon, Ive started to sketch out [some more recipes and entities of various types](https://docs.google.com/spreadsheets/d/10xhtR9kjCSgmqk_6B4KprY4cvVUWXJctRVZaNf3lPZs/edit?usp=sharing). The 'self declared verbs' and 'library verbs' tabs contain new candidates, the rest are bare bones recipe and entity sketches linked by reference. Comments and additions are very welcome.

Though we have mined entities from https://registry.tincanapi.com/, my sense – after speaking to Russell Duhon – is that we should probably be careful with that list. Many items there have been taken from a deprecated version of the activity streams spec, that point to a domain that is no longer maintained, and the definitions refer to entity types ("target") that have nothing to do with xAPI. I'd suggest deprecating the http://activitystrea.ms/ URIs and replace them with our own, but I'd love to hear opinions first.

**Comment by garemoko** [comment]
There's no problem using the activity streams IRIs. They don't resolve (and never did, it's not that these have fallen out of maintenance), but there are no systems I'm aware of that fetch verb and activity type IRIs anyway. See this blog from October 2012 for an explanation for why creating new verbs etc. when existing ones are already in use is a bad idea: https://tincanapi.com/whats-up-with-verbs-in-95/

See also https://tincanapi.com/tin-can-vs-activity-streams/ I actually discouraged the use of activity streams verbs when this blog first came out, but now that people are using them, it makes sense to continue to do so. 

In regards to https://registry.tincanapi.com/ itself, it may not be perfect, but it's the most complete list of xAPI identifiers available. We should certainly use it and add our identifiers to the list there.

**Comment by wilmTap** [comment]
It's not a blocker, and it's true that resolvability is a nice to have. 

However, I personally have found that relating your own vocab items to general vocab items (such as the activitystreams ones) rather than using them directly can insulate you from squashing the semantics, and from drift in datasets you don't control, while still being able to play nicely with others. Not religious about it, though; happy to go with the balance of opinion.

**Comment by wilmTap** [comment]
#38
