### ISSUE TITLE
http://xapi.jisc.ac.uk/extensions/vle_mod_id should be optional

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#63]
Not all organizations will have a short id for the Learning Programmes represented by their Moodle course sites. Therefore this extension should be optional. 

https://github.com/jlowe64/moodle-logstore_xapi/issues/65

**Comment by wilmTap** [comment]
To my reading, http://xapi.jisc.ac.uk/extensions/vle_mod_id is a plugin specific extension, and therefore not required. We do need to make that clearer in the documentation, though.
