### ISSUE TITLE
change identifier for http://xapi.jisc.ac.uk/extensions/vle_mod_id

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#64]
At the JISC hackathon it was proposed to change http://xapi.jisc.ac.uk/extensions/vle_mod_id to https://w3id.org/learning-analytics/learning-management-system/short-id because "mod" has such an ambiguous meaning and "vle" is tied to academia (and it's not really a vle, it's a programme id). 

https://github.com/jlowe64/moodle-logstore_xapi/issues/65

**Comment by michaelwebbjisc** [comment]
Just to clarify - it's not a programme id, at least not in UK academia lingo. It's definitely meant to hold the VLE course's module id, as defined in our UDD.  But I don't think that means we can't call it https://w3id.org/learning-analytics/learning-management-system/short-id.  Just don't want to confuse.

**Comment by garemoko** [comment]
I still dont understand what this is. Lets discuss this week.

**Comment by michaelwebbjisc** [comment]
OK! But just in case anyone else is reading this: it links to:
https://github.com/jiscdev/analytics-udd/blob/master/udd/module_vle_map.md

**Comment by wilmTap** [comment]
@garemoko In most, but not all, of UK HE, "course" refers to a multi-year programme leading to a degree, and "module" to a standalone unit that makes up such a course; you typically have about eight or so per year. 

The issue we've struggled with, and which this extension is designed to address, is the fact that a VLE course area is often, but not always, the same thing as a module. For that reason, keeping track of the connection between the two is quite important.
