### ISSUE TITLE
parent, grouping and category context activities use in the original plugin should be retained. 

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#65]
Parent/grouping/category context activities are useful for systems querying using xAPI to filter grouping of data relating to a particular technology (.e.g. Moodle or Blackboard), a particular site and/or a particular LMS course site. 

Currently in the plugin these are bloated with unnecessary extensions; I'll raise another issue in regards to these extensions.

**Comment by michaelwebbjisc** [comment]
We're not using these at the moment, so not necessary for Blackboard plugin for now.

**Comment by wilmTap** [comment]
For the Jisc xAPI recipes, we'll mark them as optional. Whether they're kept in the plugin is probably best discussed in that repo.
