### ISSUE TITLE
http://xapi.jisc.ac.uk/extensions/duedate should contain value directly rather than an object

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#66]
Related to https://github.com/jiscdev/xapi-vle/issues/47
See https://github.com/jlowe64/moodle-logstore_xapi/issues/66

**Comment by wilmTap** [comment]
See also issue #47 
Addressed in [the associated commit](https://github.com/jiscdev/xapi-vle/commit/4ba28ec91aed078cb0d51523abebd526e1b4373c)
