### ISSUE TITLE
Account IFI should not be a requirement of the recipe

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#68]
LMSs use a variety of different ways to identify users. Some use email; this should be allowed. 

When this gets down to plugins, this should either be a config setting or a fixed thing, depending on the specifics of the implementing LMS.

**Comment by michaelwebbjisc** [comment]
From a Jisc service perspective it is mandatory, so we need make sure we don't lose that information.

**Comment by garemoko** [comment]
What's mandatory? That there is an identifier or which identifier is used?

What I'm saying here is, yes there needs to be an identifier, but individual LMS/VLE installs should be allowed to choose which identifier to use.

**Comment by michaelwebbjisc** [comment]
From a Jisc service perspective, the IFI must be account, not mbox, mbox_sha1sum or openid.

**Comment by michaelwebbjisc** [comment]
Should add ... what I mean is, the documentation needs to be clear that if you want to be part of the Jisc architecture, IFI must be account, if you aren't part of the Jisc architecture it can be any of the valid IFI's.

**Comment by garemoko** [comment]
Makes sense. Is there any requirement that the value of account.name should be anything in particular?

Possible values from Moodle would be id (the key of the record in mdl_user table), username or external id (which may not always be populated).

**Comment by wilmTap** [comment]
Since these recipes document the Jisc profile, I think it'd be clearest if we just name account as mandatory.

**Comment by garemoko** [comment]
If we go down that route (which i don't necessarily object to) we'd have to be clear that for the actual plugins it would be possible to configure them in a way that is non-conformant with the JISC profile so that people using email as the identifier in their ecosystem could.

**Comment by MiroslavKratchounov** [comment]
account.name is of type string so it can be anything (email, username) that uniquely identifies an user for the specific domain (account.homePage).
