### ISSUE TITLE
Multiple issues in assignment graded

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#69]
Assignment graded should use the verb http://adlnet.gov/expapi/verbs/scored since the event is saying that the actor scored a certain value for the assignment. 

The result object should include scaled, raw, min and max score, success, and response (the instructor's feedback). 

Completion should not be sent in this statement because that should come in assignment submitted. 

The context should include the instructor who graded the assignment.

**Comment by wilmTap** [comment]
cf #70 for completion

**Comment by MiroslavKratchounov** [comment]
I don't want to rush into conclusions and mark something as a bug. I think both scored and evaluated  (as per the original Moodleroom recipe) verbs may be applicable. In some cases an assignment is evaluated and marked as completed by instructors. In other cases a student scored a certain value for assignment which has not been graded by instructor hence no feedback as response has been provided.

**Comment by garemoko** [comment]
If you read the description of the evaluated verb (which I wrote) by going to the [verb IRI](http://www.tincanapi.co.uk/pages/verbs.html#evaluated) it's pretty clear that it's intended to be used in statements where the object is a statement reference rather than an activity.

**Comment by wilmTap** [comment]
Following discussion, we've kept the http://adlnet.gov/expapi/verbs/scored verb and its associated result entity. Problem is, many of the assignments that are graded in UK HE have a non-numeric score. We've dealt with that in the result entity with a 'grade' property extension, but the definition of http://adlnet.gov/expapi/verbs/scored still mentions a numeric result. We'll try to see whether we can lobby to have that broadened to "alphanumeric result", but if that doesn't work, we might have to coin our own.

**Comment by arc12** [comment]
fyi - an open badges recipe for a related situation, and extension of result
https://openbadgespec.org/xapi/
