### ISSUE TITLE
Documentation should describe Moodle and Blackboard interface mappings

### ISSUE THREAD

**Issue by christoffballard** [jiscdev/xapi-vle#7]
The rules used to map data from Moodle and Blackboard activity logs to xAPI statements by the interfaces should be documented. There are undoubtedly assumptions which have been made in the interfaces which may affect how the data is interpreted further downstream. Examples include: what log entries are mapped to xAPI; how codes used in Moodle are translated to xAPI fields and codes; local customisation which may affect the data we receive.

**Comment by wilmTap** [comment]
Can we address this by including some of the conversion mapping information from the [test route document](https://github.com/jiscdev/vle-xapi-conversions/blob/master/moodle/route1.md) in the complete, platform specific examples linked off the recipes?
