### ISSUE TITLE
Switching persistent URI scheme

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/xapi-vle#73]
So far, we've been using made up URIs of the form http://xapi.jisc.ac.uk/ for the vocabulary items we've minted ourselves. They don't resolve at the moment, but could do that in the future- maybe...

Alternatively, we can now use a https://w3id.org/la/jisc/ scheme I've set up. At the moment, that resolves to our vocabulary page. We'll build in some more anchors to take you from, say, https://w3id.org/la/jisc/extensions/courseArea to its definition. We could easily do some content negotiation and let clients who want JSON represtentations of those definitions get them in that form.

Switching to https://w3id.org/la/jisc/ would mean changing the existing URIs, however. On the other hand, if we're going to make a switch to a persistent URI scheme, we'd better do it now.

Views?

**Comment by garemoko** [comment]
Two views on either side of the argument:

1. I think it's early enough to switch and totally agree with "if we're going to make a switch to a persistent URI scheme, we'd better do it now".

2. I'm generally skeptical of persistent URIs after the purl.org debacle. Nothing lasts forever. The question  really is which will last longest, w3id.org or jisc.ac.uk? 

`The letters 'w3' in the domain name for this site stand for "World Wide Web". Other than hosting the software for the Permanent Identifier Community Group, the "World Wide Web Consortium" (W3C) is not involved in the support or management of this website in any way.`

**Comment by arc12** [comment]
The response to #2 depends on who you ask, but based purely on longevity to date, the best evidence seems to be that jisc.ac.uk will persist (more than 20 years old. AFAIK)

What would be really good would be for Janet to provide persistent URI service; history shows that although jisc.ac.uk is persistent, management of its web estate has generally not involved URL persistence.

Adam

**Comment by wilmTap** [comment]
I know that @michaelwebbjisc is pursuing the option of Jisc providing resolvable persistent URIs at http://xapi.jisc.ac.uk/, but I'm not sure how tractable that is proving to be. 

Nonetheless, given the scepticism I'm hearing about w3id.org, perhaps sticking with http://xapi.jisc.ac.uk/ (resolvable or not) might suit our needs better. I'll go with that option in the pull request we'll put out shortly.
