### ISSUE TITLE
Add extension http://xapi.jisc.ac.uk/info to vocabulary

### ISSUE THREAD

**Issue by MiroslavKratchounov** [jiscdev/xapi-vle#78]
The http://lrs.learninglocker.net/define/extensions/info most probably needs to change to http://xapi.jisc.ac.uk/info. This extension is used by both Blackboard and Moodle.

**Comment by arc12** [comment]
@MiroslavKratchounov - I thought that was an extension for the Moodle plugin information and that Bb would have its own extension. i.e. that the keys and values inside it are specific to each plugin/platform

Both Moodle and Bb xAPI adaptors may emit the same kind of information but the content (both structure and semantics) is platfom specific, so a different extension URI makes sense to me. We only need consistency where there is commonality, IMO.

Adam

**Comment by MiroslavKratchounov** [comment]
I'm suggesting just to have the same extension key and the value can be any Json value with platform specific data.

**Comment by MiroslavKratchounov** [comment]
Probably a better name would be http://xapi.jisc.ac.uk/plugin/info. I suppose all URI's with their descriptions will be hosted at http://xapi.jisc.ac.uk and IMHO it makes sense to have a common one for all adaptors.

**Comment by wilmTap** [comment]
Leave as is for now.
