### ISSUE TITLE
Generic object type definition which is supplier and institution agnostic

### ISSUE THREAD

**Issue by christoffballard** [jiscdev/xapi-vle#8]
To ensure standardisation of the use of xAPI and to make it easier to have a consistent interpretation across different sites, we think object types should be defined at a higher and more generic level. Local Moodle and Blackboard objects would then be mapped to these object types. Otherwise we will have to have different approaches depending on whether Moodle or Blackboard is used, and possibly across different institutions too.

Currently there are a large number of object types with potentially overlapping definitions. This leads to questions such as, how does a forum_discussion differ from a forum? What is the difference between a book and a page? Presumably these relate to specific Moodle functionality.

The purpose and use of each object type should be clearly defined.

**Comment by ds10** [comment]
I think the [vocab document](url) is a start for this. I guess we need to 1)write the object type definitions up and 2)for things we are newly minting check if definitions already exist that we can use.
